version: '3'
services:
  redis:
    image: 'bitnami/redis:latest'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - ${REDIS_PORT}:6379
  sql:
    image: postgres:latest
    restart: always
    ports:
      - ${SQL_PORT}:5432
    environment:
      POSTGRES_PASSWORD: "${SQL_PASSWORD}"
      POSTGRES_DB: "${SQL_DATABASE}"
      POSTGRES_USER: "${SQL_USER}"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - sql
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    environment:
      CLIENT_PORT: "${CLIENT_PORT}"
